import type { Project, Skill, Achievement, Certification, Activity, NavItem, TimelineEntry } from '@/types';

export const PERSONAL = {
  name: 'Ansh Tripathi',
  tagline: 'AI/ML Engineer · Full Stack Developer · Problem Solver',
  description: `B.Tech CSE (AI/ML) student at Lovely Professional University, building at the intersection of machine learning, real-time systems, and modern web. Passionate about translating complex algorithms into production-grade software.`,
  email: 'ansh10tripathi@gmail.com',
  phone: '+91-8081314040',
  github: 'https://github.com/ansh10tripathi',
  linkedin: 'https://linkedin.com/in/ansh-tripathi10',
  university: 'Lovely Professional University',
  degree: 'B.Tech – CSE (AI/ML Specialization)',
  cgpa: '7.4',
  scholarship: 'LPUNEST Category 1 — 30% Tuition Waiver',
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '#hero' },
  { label: 'About', href: '#about' },
  { label: 'Skills', href: '#skills' },
  { label: 'Projects', href: '#projects' },
  { label: 'GitHub', href: '#github' },
  { label: 'Contact', href: '#contact' },
];

export const PROJECTS: Project[] = [
  {
    id: 'smartgrid',
    title: 'SmartGrid-GOA-LoadBalancing',
    tagline: 'ML-powered smart grid energy optimizer',
    description: `An intelligent energy distribution system using the Grasshopper Optimization Algorithm (GOA) to balance electrical load across grid nodes. Simulates dynamic multi-node allocation to minimize power imbalance and maximize system stability.`,
    tech: ['Python', 'Machine Learning', 'GOA', 'NumPy', 'Matplotlib'],
    github: 'https://github.com/ansh10tripathi/SmartGrid-GOA-LoadBalancing',
    category: 'AI / Optimization',
    highlight: 'Bio-inspired ML meets real-world energy systems',
    date: 'March 2026',
    badge: 'Featured',
    color: '#00F5FF',
    icon: '⚡',
  },
  {
    id: 'solubility',
    title: 'Chemical-Solubility-ML-Model',
    tagline: 'Regression pipeline for molecular property prediction',
    description: `End-to-end ML regression pipeline predicting chemical solubility (LogS) using Linear Regression and Random Forest. Includes full EDA, preprocessing, feature importance analysis, and visual evaluation (R², RMSE, MAE).`,
    tech: ['Python', 'Scikit-learn', 'Pandas', 'Matplotlib', 'Jupyter'],
    github: 'https://github.com/ansh10tripathi/Chemical-Solubility-ML-Model',
    category: 'Machine Learning',
    highlight: 'Full ML workflow from raw data to model evaluation',
    date: 'February 2026',
    badge: 'ML',
    color: '#10B981',
    icon: '🧪',
  },
  {
    id: 'priority-inversion',
    title: 'Priority-Inversion-Handling-System',
    tagline: 'Real-time OS scheduler with PIP & PCP protocols',
    description: `Simulates the classic priority inversion problem in real-time systems and implements Priority Inheritance Protocol (PIP) and Priority Ceiling Protocol (PCP) to resolve scheduling conflicts using mutex locks, semaphores, and synchronization.`,
    tech: ['Python', 'RTOS Simulation', 'Concurrency', 'Mutex', 'Semaphores'],
    github: 'https://github.com/ansh10tripathi/priority-inversion-handling-system',
    category: 'Systems Programming',
    highlight: 'OS kernel-level scheduling logic in pure Python',
    date: 'March 2026',
    badge: 'Systems',
    color: '#F43F5E',
    icon: '⚙️',
  },
  {
    id: 'bidwise',
    title: 'BidWise-RTB-Engine',
    tagline: 'AI-driven real-time bidding auction simulator',
    description: `A sophisticated ad-tech simulation engine implementing DSP behavior with second-price auction logic. Features adaptive bidding strategies based on budget, conversion probability, and user data, with ROI optimization and dynamic budget allocation.`,
    tech: ['TypeScript', 'AI Optimization', 'Auction Theory', 'Node.js'],
    github: 'https://github.com/ansh10tripathi/BidWise-RTB-Engine',
    category: 'AI / Ad-Tech',
    highlight: 'Real-world ad-tech auction logic from scratch',
    date: 'February 2026',
    badge: 'AI',
    color: '#7C3AED',
    icon: '💹',
  },
  {
    id: 'productivity-hub',
    title: 'Productivity-Hub',
    tagline: 'Feature-rich task management React application',
    description: `Responsive task management app built with React and TailwindCSS featuring drag-and-drop task reordering, dark/light mode toggle, advanced filtering, and persistent local state — all with component-based architecture.`,
    tech: ['React', 'TailwindCSS', 'JavaScript', 'Drag-and-Drop'],
    github: 'https://github.com/ansh10tripathi/productivity-hub',
    category: 'Web Development',
    highlight: 'Production-quality React DX with full state management',
    date: 'February 2026',
    badge: 'Web',
    color: '#4F46E5',
    icon: '🎯',
  },
];

export const SKILLS = {
  languages: [
    { name: 'Python', level: 90, icon: 'python' },
    { name: 'C++', level: 82, icon: 'cplusplus' },
    { name: 'JavaScript', level: 80, icon: 'javascript' },
    { name: 'TypeScript', level: 72, icon: 'typescript' },
    { name: 'Java', level: 70, icon: 'java' },
    { name: 'C', level: 75, icon: 'c' },
  ] as Skill[],
  ml: [
    { name: 'NumPy', level: 88, icon: 'numpy' },
    { name: 'Pandas', level: 85, icon: 'pandas' },
    { name: 'Scikit-learn', level: 78, icon: 'scikitlearn' },
    { name: 'Matplotlib', level: 82, icon: 'matplotlib' },
    { name: 'Jupyter', level: 88, icon: 'jupyter' },
    { name: 'Google Colab', level: 85, icon: 'googlecolab' },
  ] as Skill[],
  web: [
    { name: 'React', level: 82, icon: 'react' },
    { name: 'Next.js', level: 70, icon: 'nextdotjs' },
    { name: 'TailwindCSS', level: 88, icon: 'tailwindcss' },
    { name: 'Flask', level: 75, icon: 'flask' },
    { name: 'FastAPI', level: 72, icon: 'fastapi' },
    { name: 'HTML/CSS', level: 90, icon: 'html5' },
  ] as Skill[],
  tools: [
    { name: 'Git', level: 85, icon: 'git' },
    { name: 'GitHub', level: 90, icon: 'github' },
    { name: 'PostgreSQL', level: 72, icon: 'postgresql' },
    { name: 'VS Code', level: 92, icon: 'vscode' },
    { name: 'Linux', level: 70, icon: 'linux' },
  ] as Skill[],
};

export const ACHIEVEMENTS: Achievement[] = [
  {
    title: 'LPUNEST Category 1 Scholar',
    description: 'Top merit tier in national-level engineering entrance — 30% tuition fee waiver',
    icon: '🏆',
    color: '#F59E0B',
  },
  {
    title: 'Adobe India Hackathon',
    description: 'Cleared Round 1 Online MCQ Assessment — Certificate awarded',
    icon: '🎖️',
    color: '#FF0000',
  },
  {
    title: '10+ Public GitHub Repos',
    description: 'Active open-source contributor with MIT-licensed, well-documented projects since July 2024',
    icon: '💻',
    color: '#00F5FF',
  },
  {
    title: 'District-Level Athlete',
    description: 'Represented school in Shot Put, Javelin, Volleyball & Football at inter-school district level',
    icon: '🏅',
    color: '#10B981',
  },
  {
    title: 'Matriculation — 91%',
    description: 'Little Flower School, Siddharth Nagar — March 2022',
    icon: '📚',
    color: '#7C3AED',
  },
];

export const CERTIFICATIONS: Certification[] = [
  {
    title: 'Linux Fundamentals',
    issuer: 'Skillera',
    duration: 'Sept 2024 – Nov 2024',
    icon: '🐧',
    color: '#F59E0B',
  },
  {
    title: 'AI Tools Workshop',
    issuer: 'All AI Tools Tech Challenge',
    duration: '2025',
    icon: '🤖',
    color: '#00F5FF',
  },
  {
    title: 'Trinetra Hackathon',
    issuer: 'Participation Certificate',
    duration: '2025',
    icon: '⚡',
    color: '#7C3AED',
  },
  {
    title: "Just In Case '25",
    issuer: 'Global Case Competition',
    duration: '2025',
    icon: '🌍',
    color: '#10B981',
  },
];

export const ACTIVITIES: Activity[] = [
  {
    role: 'Member — Excel to Accelerate Club',
    description: 'Contributing to technical and collaborative initiatives within the university tech community.',
    year: '2024–Present',
    type: 'Club',
  },
  {
    role: 'Team Apex Member',
    description: 'Group-based technical project collaboration and competitive problem-solving team.',
    year: '2024–Present',
    type: 'Team',
  },
];

export const TIMELINE_ENTRIES: TimelineEntry[] = [
  // ── 2026 ──────────────────────────────────────────────────────────────────
  {
    year: '2026',
    title: 'SmartGrid-GOA-LoadBalancing',
    subtitle: 'ML-based smart grid optimizer using Grasshopper Optimization Algorithm',
    org: 'Personal Project',
    date: 'March 2026',
    type: 'Project',
    description: 'Bio-inspired load balancing across grid nodes — minimizes power imbalance and maximizes system stability.',
    icon: '⚡',
    color: '#00F5FF',
  },
  {
    year: '2026',
    title: 'Priority-Inversion-Handling-System',
    subtitle: 'Real-Time OS Simulation with PIP & PCP protocols',
    org: 'Personal Project',
    date: 'March 2026',
    type: 'Project',
    description: 'Simulates mutex lock contention and resolves scheduling conflicts using Priority Inheritance and Ceiling protocols.',
    icon: '⚙️',
    color: '#F43F5E',
  },
  {
    year: '2026',
    title: 'BidWise-RTB-Engine & Chemical-Solubility-ML-Model',
    subtitle: 'AI ad-tech simulation + ML regression pipeline',
    org: 'Personal Projects',
    date: 'February 2026',
    type: 'Project',
    description: 'Second-price auction DSP simulator and end-to-end solubility prediction pipeline with R², RMSE, MAE evaluation.',
    icon: '🚀',
    color: '#7C3AED',
  },
  // ── 2025 ──────────────────────────────────────────────────────────────────
  {
    year: '2025',
    title: 'Adobe India Hackathon — Round 1 Cleared',
    subtitle: 'Passed the online MCQ assessment — Certificate awarded',
    org: 'Adobe',
    date: '2025',
    type: 'Achievement',
    description: 'Cleared the competitive Round 1 online assessment out of thousands of applicants nationwide.',
    icon: '🏆',
    color: '#F43F5E',
  },
  {
    year: '2025',
    title: 'AI Tools Workshop & Trinetra Hackathon',
    subtitle: 'Certificates of completion and participation awarded',
    org: 'Various',
    date: '2025',
    type: 'Certification',
    description: 'Completed AI tools challenge and participated in Trinetra hackathon — both certificates awarded.',
    icon: '🤖',
    color: '#7C3AED',
  },
  // ── 2024 ──────────────────────────────────────────────────────────────────
  {
    year: '2024',
    title: 'Excel to Accelerate Club + Team Apex',
    subtitle: 'Technical initiatives, group projects, and collaborative engineering',
    org: 'Lovely Professional University',
    date: '2024–Present',
    type: 'Activity',
    description: 'Active member of two university technical communities — contributing to collaborative projects and competitive problem-solving.',
    icon: '👥',
    color: '#10B981',
  },
  {
    year: '2024',
    title: 'Linux Fundamentals — Skillera',
    subtitle: 'Completed Linux system administration fundamentals',
    org: 'Skillera',
    date: 'Sept–Nov 2024',
    type: 'Certification',
    description: 'Covered file systems, process management, shell scripting, networking, and system administration.',
    icon: '🐧',
    color: '#F59E0B',
  },
  {
    year: '2024',
    title: 'B.Tech CSE (AI/ML) — Lovely Professional University',
    subtitle: 'LPUNEST Category 1 Scholar — 30% Tuition Waiver',
    org: 'Lovely Professional University',
    date: 'July 2024',
    type: 'Education',
    description: 'Pursuing B.Tech in Computer Science with AI/ML specialization. Secured Category 1 scholarship through LPUNEST.',
    icon: '🎓',
    color: '#00F5FF',
  },
];

export const GITHUB_FALLBACK = {
  publicRepos: 10,
  followers: 5,
  totalStars: 12,
  totalForks: 3,
};

export const LANGUAGE_COLORS: Record<string, string> = {
  Python: '#3572A5',
  TypeScript: '#2b7489',
  JavaScript: '#f1e05a',
  Java: '#b07219',
  'C++': '#f34b7d',
  C: '#555555',
  HTML: '#e34c26',
  CSS: '#563d7c',
  Shell: '#89e051',
  Jupyter: '#DA5B0B',
};
